version: '3.3'
services:
  # ----- reverse-proxy --------------------------------------------------------
  traefik:
    image: "traefik:2.0"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:80"
      - "9080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      
  # ----- autocomplete addr ----------------------------------------------------
  autocomplete-addr-postgis:
    build: ./nextmoov-smop-autocomplete-addr/postgis
    volumes:
      - autocomplete-addr-postgis:/var/lib/postgresql/data
    #ports:
      #- "5432:5432"

  autocomplete-addr-elastic:
    image: elasticsearch:6.4.3
    environment:
      - discovery.type=single-node
    volumes:
      - autocomplete-addr-elastic:/usr/share/elasticsearch/data
    #ports:
      #- "9200:9200"

  autocomplete-addr-importer:
    build: ./nextmoov-smop-autocomplete-addr/importer
    depends_on:
      - autocomplete-addr-postgis
      - autocomplete-addr-elastic
    volumes:
      - autocomplete-addr-importer:/app/tmp

  autocomplete-addr-api:
    build: ./nextmoov-smop-autocomplete-addr/api
    depends_on:
      - autocomplete-addr-importer
      - autocomplete-addr-postgis
      - autocomplete-addr-elastic
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.http.routers.autocomplete-addr-api.entrypoints=web"
      - "traefik.http.routers.autocomplete-addr-api.rule=PathPrefix(`/autocomplete/address`)"
    #ports:
      #- "8084:80"

volumes:
  autocomplete-addr-postgis:
  autocomplete-addr-elastic:
  autocomplete-addr-importer:  
